services:
  - type: web
    name: alpha-circle-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd bot && python bot.py
    healthCheckPath: /
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: SUPPORT_USERNAME
        value: "@crypto_guy02"
      - key: MIN_MC
        value: "10000"
      - key: MAX_MC
        value: "800000"
      - key: SCAN_INTERVAL
        value: "300"
      - key: SEND_INTERVAL_MIN
        value: "60"
      - key: SEND_INTERVAL_MAX
        value: "180"
