services:
  - type: worker
    name: alpha-circle-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
      - key: SUPPORT_USERNAME
        value: "@crypto_guy02"
      - key: MIN_MC
        value: "120000"
      - key: MAX_MC
        value: "50000000"
      - key: GAIN_THRESHOLD_PCT
        value: "20"
      - key: SCAN_INTERVAL
        value: "300"
      - key: SEND_INTERVAL_MIN
        value: "120"
      - key: SEND_INTERVAL_MAX
        value: "420"
